import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/toaster";
import RootSessionProvider from "@/context/SessionProvider";
import { ThemeProvider } from "@/components/ThemeProvider/theme-provider";
import RootThemeProvider from "@/context/ThemeProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-[#27272a80] `}
      >
        <Toaster />
        <TooltipProvider>
          <RootSessionProvider>
            <RootThemeProvider>{children}</RootThemeProvider>
          </RootSessionProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
